[project]
name = "fastapi-mongo"
version = "0.1.0"
description = "Simple Rest API example with mongodb"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.1.0",
    "motor>=3.6.0",
]
